2022-01-06 01:31:52,527 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302868ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:03:59,905 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 922251ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:10:02,857 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302924ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:16:05,746 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302855ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:21:48,628 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:27:51,520 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302867ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:33:54,442 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302903ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:39:57,367 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:46:00,249 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302860ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:49:59,982 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 179709ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 02:55:42,856 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302854ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:07:48,753 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302948ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:13:51,703 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302917ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:19:54,608 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302882ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:25:37,481 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302848ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:31:40,372 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302873ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:37:43,263 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302860ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:43:46,175 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302891ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:49:49,073 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302873ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 03:55:31,982 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302888ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:01:34,870 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:07:37,835 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:19:43,685 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302917ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:25:46,566 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:31:29,476 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302888ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:49:38,188 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 04:55:41,082 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:01:24,133 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 303039ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:07:27,027 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302740ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:13:29,961 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302906ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:19:32,875 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:25:35,784 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302890ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:31:38,703 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302895ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:37:21,662 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302943ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:43:24,579 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302880ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:49:27,531 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302926ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 05:55:30,414 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:07:36,218 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:13:39,140 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302881ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:19:42,091 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:25:44,971 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302852ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:31:47,907 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:51:51,032 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302856ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 06:57:53,947 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302884ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:03:56,897 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:09:59,838 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:15:42,778 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302921ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:21:45,688 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302882ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:32:06,758 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 561043ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:44:12,570 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:50:15,525 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 07:55:58,433 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302888ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:02:01,369 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302911ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:08:04,270 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302886ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:14:07,168 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:20:10,134 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302947ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:25:53,057 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302887ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:31:55,948 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 08:58:22,018 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 302881ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:07:57,976 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 555934ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:11:16,005 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 158008ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:14:11,190 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 155165ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:17:12,967 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 161758ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:26:54,682 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 581705ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:34:08,683 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 413992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:38:36,025 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 247330ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:48:03,188 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 567158ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:51:06,796 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 163590ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:54:08,040 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 161229ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:56:46,940 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 138874ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 09:59:14,154 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 147210ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:05:14,084 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 161732ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:10:09,521 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 295428ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:13:03,830 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 154281ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:16:29,640 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 165774ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:19:25,233 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 155575ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:22:45,989 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 180734ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:25:56,737 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 170731ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:28:58,243 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 161489ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:31:41,301 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 143036ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:34:17,244 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 135923ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:37:40,984 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 163728ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:40:25,924 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 144902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:43:39,372 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 153418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:46:40,229 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 160839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:49:37,477 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 157234ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:52:02,764 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 145283ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:55:20,094 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 157305ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 10:58:20,344 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 160235ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:04:28,103 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 156356ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:07:28,128 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 140000ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:13:25,631 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 162515ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:16:27,673 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 162023ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:19:16,177 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 148498ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:22:02,781 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 146594ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:25:31,215 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 168407ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:28:18,409 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 147185ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:31:10,937 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 152494ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:34:21,556 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 150560ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:37:18,115 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 156545ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:40:42,197 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 164056ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:43:58,278 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 156043ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:47:02,895 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 164605ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:49:50,194 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 147276ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:53:15,570 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 165357ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:56:12,227 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 136642ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 11:59:15,174 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 162933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:05:53,306 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 163442ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:08:54,244 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 140905ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:12:01,659 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 167398ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:15:18,694 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 157006ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:18:23,639 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 164925ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:21:31,791 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 148125ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:24:29,224 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 157416ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:27:29,159 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 159908ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:30:46,823 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 157647ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:33:40,304 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 153454ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:36:28,814 ERROR 50786 nodejs.ClusterClientNoResponseError: client no response in 148470ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 50786
hostname: localhost

2022-01-06 12:39:12,084 ERROR 57972 [-/10.129.19.27/-/22954ms GET /api/sync?userName=CheeryQ] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://leetcode.com/api/submissions/?offset=100&limit=20 -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":5,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 6, socketHandledResponses: 5)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/heqiang/days/my-leetcode-helper/node_modules/urllib/lib/urllib.js:997:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ResponseTimeoutError"
requestId: 6
data: undefined
path: "/api/submissions/?offset=100&limit=20"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":5019,"keepAliveSocket":true,"requestUrls":["https://leetcode.com/api/submissions/?offset=100&limit=20"],"timing":null,"remoteAddress":"104.26.9.101","remotePort":443,"socketHandledRequests":6,"socketHandledResponses":5}
pid: 57972
hostname: MacBook-Pro.local

2022-01-06 15:32:49,105 ERROR 28777 [egg-mongoose] mongodb://127.0.0.1/leetcode disconnected
2022-01-06 15:32:49,108 ERROR 28777 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 28777
hostname: heqiangdeMacBook-Pro.local

2022-01-06 15:32:49,109 ERROR 28777 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 28777
hostname: heqiangdeMacBook-Pro.local

2022-01-06 15:32:49,112 ERROR 28777 [-/127.0.0.1/-/0ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/heqiang/codes/my-leetcode-helper/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 28777
hostname: heqiangdeMacBook-Pro.local

2022-01-06 19:53:39,637 ERROR 65536 [-/10.129.19.27/-/9ms GET /api/user/goal] nodejs.ReferenceError: findOneByUserName is not defined
    at UserController.getUserGoalInfo (/Users/heqiang/days/my-leetcode-helper/app/controller/user.js:5:18)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at next (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:45:18)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:191:33)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at Object.<anonymous> (/Users/heqiang/days/my-leetcode-helper/app/middleware/access.js:9:5)
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:65:19)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:50:10)
    at converted (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa/node_modules/koa-compose/index.js:42:32)

pid: 65536
hostname: MacBook-Pro.local

2022-01-06 19:54:32,580 ERROR 65661 [-/undefined/-/10028ms GET /api/user/goal] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
headerSent: true
pid: 65661
hostname: MacBook-Pro.local

2022-01-06 19:54:33,018 ERROR 65661 [-/undefined/-/10006ms GET /api/user/goal] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
headerSent: true
pid: 65661
hostname: MacBook-Pro.local

2022-01-06 19:54:42,622 ERROR 65661 [-/10.129.19.27/-/10007ms GET /api/user/goal] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

pid: 65661
hostname: MacBook-Pro.local

2022-01-06 19:55:18,643 ERROR 65661 [-/10.129.19.27/-/10010ms GET /api/user/goal?username=CheeryQ] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

pid: 65661
hostname: MacBook-Pro.local

2022-01-06 19:55:53,140 ERROR 65823 [-/undefined/-/10017ms GET /api/user/goal?username=CheeryQ] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
headerSent: true
pid: 65823
hostname: MacBook-Pro.local

2022-01-06 19:55:57,870 ERROR 65823 [-/undefined/-/10009ms GET /api/user/goal?userName=CheeryQ] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
headerSent: true
pid: 65823
hostname: MacBook-Pro.local

2022-01-06 19:56:01,369 ERROR 65823 [-/10.129.19.27/-/10007ms GET /api/user/goal?userName=CheeryQ] nodejs.MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

pid: 65823
hostname: MacBook-Pro.local

2022-01-06 19:57:31,397 ERROR 65959 [-/10.129.19.27/-/10030ms GET /api/user/goal?userName=CheeryQ] nodejs.MongooseError: Operation `user.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/heqiang/days/my-leetcode-helper/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

pid: 65959
hostname: MacBook-Pro.local

2022-01-06 20:03:36,676 ERROR 66188 [-/10.129.19.27/-/45ms GET /api/problems/byMonth] nodejs.ReferenceError: getSliceTimestamp is not defined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:10:29
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:8:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 66188
hostname: MacBook-Pro.local

2022-01-06 20:03:45,087 ERROR 66188 [-/10.129.19.27/-/7ms GET /api/problem/group] nodejs.TypeError: this.getAllProblemByTimeRange is not a function
    at ProblemController.getGroupedProblems (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:34:33)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at next (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:45:18)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:191:33)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at Object.<anonymous> (/Users/heqiang/days/my-leetcode-helper/app/middleware/access.js:9:5)
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:65:19)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:50:10)
    at converted (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa/node_modules/koa-compose/index.js:42:32)

pid: 66188
hostname: MacBook-Pro.local

2022-01-06 20:03:56,222 ERROR 66188 [-/10.129.19.27/-/7ms GET /api/commit/today] nodejs.ReferenceError: ctx is not defined
    at CommitController.getCommitsByDate (/Users/heqiang/days/my-leetcode-helper/app/controller/commit.js:6:21)
    at CommitController.getTodyLogs (/Users/heqiang/days/my-leetcode-helper/app/controller/commit.js:13:29)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at next (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:45:18)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:191:33)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at Object.<anonymous> (/Users/heqiang/days/my-leetcode-helper/app/middleware/access.js:9:5)
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:65:19)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:50:10)
    at converted (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:17:15)

pid: 66188
hostname: MacBook-Pro.local

2022-01-06 20:25:57,760 ERROR 67672 [-/10.129.19.27/-/55ms GET /api/problems/byMonth] nodejs.ReferenceError: getSliceTimestamp is not defined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:10:29
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:8:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 67672
hostname: MacBook-Pro.local

2022-01-06 20:26:24,570 ERROR 68756 [-/10.129.19.27/-/42ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property 'push' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:13:32
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 68756
hostname: MacBook-Pro.local

2022-01-06 20:26:48,658 ERROR 68796 [-/10.129.19.27/-/55ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property 'push' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:13:32
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 68796
hostname: MacBook-Pro.local

2022-01-06 20:27:20,701 ERROR 68840 [-/10.129.19.27/-/39ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property 'push' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:13:32
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 68840
hostname: MacBook-Pro.local

2022-01-06 20:27:51,571 ERROR 68963 [-/10.129.19.27/-/49ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property '[object Object]' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:12:19
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 68963
hostname: MacBook-Pro.local

2022-01-06 20:28:24,420 ERROR 69029 [-/10.129.19.27/-/59ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property '[object Object]' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:13:19
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 69029
hostname: MacBook-Pro.local

2022-01-06 20:29:03,886 ERROR 69116 [-/10.129.19.27/-/54ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property '1641052800' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:12:19
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 69116
hostname: MacBook-Pro.local

2022-01-06 20:29:56,130 ERROR 69214 [-/10.129.19.27/-/56ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property '1641052800' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:12:19
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 69214
hostname: MacBook-Pro.local

2022-01-06 20:30:37,649 ERROR 69291 [-/10.129.19.27/-/55ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property '1641052800' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:12:19
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 69291
hostname: MacBook-Pro.local

2022-01-06 20:31:15,888 ERROR 69339 [-/10.129.19.27/-/40ms GET /api/problems/byMonth] nodejs.ReferenceError: Cannot access 'cate' before initialization
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:20:46
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 69339
hostname: MacBook-Pro.local

2022-01-06 20:31:33,462 ERROR 69392 [-/10.129.19.27/-/55ms GET /api/problems/byMonth] nodejs.TypeError: Cannot read property '1641052800' of undefined
    at /Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:12:19
    at Array.reduce (<anonymous>)
    at ProblemController.getAllProblemByMonth (/Users/heqiang/days/my-leetcode-helper/app/controller/problem.js:9:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 69392
hostname: MacBook-Pro.local

2022-01-06 20:41:47,434 ERROR 70046 [-/10.129.19.27/-/20ms GET /api/commit/today] nodejs.ReferenceError: ctx is not defined
    at CommitController.getCommitsByDate (/Users/heqiang/days/my-leetcode-helper/app/controller/commit.js:6:21)
    at CommitController.getTodyLogs (/Users/heqiang/days/my-leetcode-helper/app/controller/commit.js:13:29)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/heqiang/days/my-leetcode-helper/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at next (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:45:18)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:44:32)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/@eggjs/router/lib/router.js:191:33)
    at dispatch (/Users/heqiang/days/my-leetcode-helper/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at Object.<anonymous> (/Users/heqiang/days/my-leetcode-helper/app/middleware/access.js:9:5)
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:65:19)
    at /Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/heqiang/days/my-leetcode-helper/node_modules/co/index.js:50:10)
    at converted (/Users/heqiang/days/my-leetcode-helper/node_modules/koa-convert/index.js:17:15)

pid: 70046
hostname: MacBook-Pro.local

2022-01-06 21:04:43,105 ERROR 72250 [-/10.129.19.27/-/20ms GET /api/commit/today] nodejs.ReferenceError: log is not defined
    at CommitController.getTodayLogs (/Users/heqiang/days/my-leetcode-helper/app/controller/commit.js:16:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

pid: 72250
hostname: MacBook-Pro.local

